name: tuples
description: Collection of Kotlin-inspired named tuples (from Pair to Sextuple)
version: 2.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  meta: ^1.7.0
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.1
